Hacemus
Aivoapina/imneversorry pull request #59
Opened 2020-12-04 10:48 UTC by eltsu7

https://t.me/c/1363070040/153134

2020-12-04 11:05 UTC, Cadiac requested changes

2020-12-04 11:05 UTC, Cadiac commented on teekkari.py
> +            txtHyyvä = 'hy-wae'
```suggestion
            txtHyyva = 'hy-wae'
```

2020-12-04 11:05 UTC, Cadiac commented on teekkari.py
> +            txtHyyvä = 'hyy-vä'
```suggestion
            txtHyyva = 'hyy-vä'
```

2020-12-04 11:05 UTC, Cadiac commented on teekkari.py
> +                bot.sendMessage(chat_id=update.message.chat_id, text=txtHyyvä)
```suggestion
                bot.sendMessage(chat_id=update.message.chat_id, text=txtHyyva)
```

2020-12-04 11:14 UTC, Cadiac approved these changes
Looks guud to me :DDD

2020-12-23 16:01 UTC, Aivoapina approved these changes

2020-12-23 16:01 UTC, merged